import express from 'express';
const router = express.Router();
import authRoutes from './auth.routes';
import permissionRoutes from './permissions.routes';
import installerRoutes from './installer.routes';
import customerRoutes from './customer.routes';
import salesPersonRoutes from './salesPerson.routes';
import quotesRoutes from './quotient.routes';
import invoiceRoutes from './invoice.routes';
import calenderRoutes from './calender.routes';
import chatRotes from "./chat.routes";
import messageRoutes from "./message.routes";
import usersRoutes from "./users.routes";
import dashboardRoutes from './dashboard.routes';
import contactFormRoutes from './contactForm.routes';
import rolesRoutes from './roles.routes';
import visitorLogsRoutes from './visitorLogs.routes';
import paymentHistoryRoutes from './paymentHistory.routes';
import quoteChatRoutes from './quoteChat.routes';
import ductedAssessmentRoutes from './ductedAssessment.routes';
import popupFormRoutes from './popupForm.routes';
import customInvoiceRoutes from "./customInvoice.routes";
import notificationRoutes from "./notification.routes";
import documentsRoutes from './documents.routes';
import productItemsRoutes from './productItems.routes';
import companyRoutes from './company.routes';
import stockOrderRoutes from './stockOrder.routes';
import logsRoutes from './logs.routes';
import systemRoutes from './system.routes';
import leadsRoutes from './leads.routes';
import leadsController from '@controllers/leads.controller';
import taskRoutes from './task.routes';
import activityTrackerRoutes from './activityTracker.routes';
import salaryRoutes from './salary.routes';
import hrRoutes from './hr.routes';
import trainingRoutes from './training.routes';
import feedbackRoutes from './feedback.routes';
import expenseRoutes from './expense.routes';
import financeRoutes from './finance.routes';
import adminRoutes from './admin.routes';
import installerAgreementRoutes from './installerAgreement.routes';
import customContactRoutes from './customContact.routes';
import assessmentRoutes from './assessment.routes';
import allInOneJobRoutes, { allInOneJobPublicRouter } from './allInOneJob.routes';
import siteInfoRoutes from './siteInfo.routes';
import productRoutes from './product.routes';
import quoteWorkflowRoutes from './quoteWorkflow.routes';
import solarRoutes from './solar.routes';
import crmSettingsRoutes from './crmSettings.routes';
import calculatorPricingRoutes from './calculatorPricing.routes';
import crmCompanyUnitRoutes from './crmCompanyUnit.routes';
import crmSettingsController from '@controllers/crmSettings.controller';
import crmCompanyUnitController from '@controllers/crmCompanyUnit.controller';
import slaRoutes from './sla.routes';
import masterTaskRoutes from './masterTask.routes';
import letterStudioRoutes from './letterStudio.routes';
router.get('/',(req,res)=>{
    res.send("OK")
})
router.get("/public/branding", crmSettingsController.getPublicBranding.bind(crmSettingsController));
router.get("/public/company-branding", crmCompanyUnitController.getPublicBranding.bind(crmCompanyUnitController));
router.use('/auth', authRoutes);
router.use('/v1/permission',permissionRoutes);
router.use('/v1/installer',installerRoutes);
router.use('/v1/customer',customerRoutes);
router.use('/v1/sales-person',salesPersonRoutes);
router.use('/quotes', quotesRoutes);
router.use('/invoice',invoiceRoutes);
router.use('/v1/calender',calenderRoutes);
router.use("/v1/chats",chatRotes);
router.use('/v1/message', messageRoutes);
router.use("/v1/users",usersRoutes)
router.use('/v1/dashboard', dashboardRoutes);
router.use('/contact-form', contactFormRoutes);
router.use('/v1/roles', rolesRoutes);
router.use('/visitor-logs',visitorLogsRoutes);
router.use('/v1/payment-history',paymentHistoryRoutes);
router.use('/quote-chat',quoteChatRoutes);
router.use('/ducted-assessment',ductedAssessmentRoutes);
router.use('/popup-form',popupFormRoutes);
router.use('/custom-invoice',customInvoiceRoutes);
router.use('/notifications',notificationRoutes);
router.use('/v1/documents',documentsRoutes);
router.use('/v1/product-items',productItemsRoutes);
router.use('/v1/company',companyRoutes);
router.use('/stock-order',stockOrderRoutes);
router.use('/v1/system-logs',logsRoutes);
router.use('/v1/system',systemRoutes);
router.post('/leads/public-enquiry', leadsController.publicEnquiry.bind(leadsController));
router.get('/leads/webhooks/:channel', leadsController.ingestWebhook.bind(leadsController));
router.post('/leads/webhooks/:channel', leadsController.ingestWebhook.bind(leadsController));
router.use('/v1/leads',leadsRoutes);
router.use('/v1/tasks',taskRoutes);
router.use('/v1/activity-tracker',activityTrackerRoutes);
router.use('/v1/salaries',salaryRoutes);
router.use('/v1/hr', hrRoutes);
router.use('/v1/training', trainingRoutes);
router.use('/v1/feedback', feedbackRoutes);
router.use('/v1/expenses',expenseRoutes);
router.use('/v1/finance',financeRoutes);
router.use('/v1/admin',adminRoutes);
router.use('/v1/installer-agreement',installerAgreementRoutes);
router.use('/v1/custom-contact',customContactRoutes);
router.use('/v1/assessment',assessmentRoutes);
router.use('/v1/all-in-one-jobs', allInOneJobRoutes);
router.use('/all-in-one-jobs', allInOneJobPublicRouter);
router.use('/site-info',siteInfoRoutes);
router.use('/v1/products',productRoutes);
router.use('/v1/workflows',quoteWorkflowRoutes)
router.use('/v1/solar', solarRoutes);
/* ── CRM core (branding, companies, SLA, master tasks) ── */
router.use('/v1/crm-settings', crmSettingsRoutes);
router.use('/v1/crm-companies', crmCompanyUnitRoutes);
router.use('/v1/calculator', calculatorPricingRoutes);
router.use('/v1/sla', slaRoutes);
router.use('/v1/master-tasks', masterTaskRoutes);
router.use('/v1/letter-studio', letterStudioRoutes);
export default router;