import quotesController from '@controllers/quotes.controller';
import express from 'express';
import { bypassValidation } from 'src/middleware/bypass_token.middleware';
const router = express.Router();

router.post("/v1/add", quotesController.addNew.bind(quotesController));
router.post("/v1/add-attachments", quotesController.addAttachments.bind(quotesController));
router.put("/v1/:quoteId/manual-attachments", quotesController.updateManualAttachments.bind(quotesController));
router.put("/v1/:quoteId/green-sketch", quotesController.updateGreenSketch.bind(quotesController));
router.post("/v1/solar-quote", quotesController.createSolarQuote.bind(quotesController));
router.post("/v1/solar-quote/send-email", quotesController.sendSolarQuoteEmail.bind(quotesController));
router.post("/v1/solar-quotes", quotesController.getSolarQuotes.bind(quotesController));
/** Public Share Proposal — no JWT; requires Mongo _id + numeric id to both match. */
router.get("/solar-proposal/:objectId/:quoteId", quotesController.getSolarProposal.bind(quotesController));
router.put("/v1/update-quote", quotesController.update.bind(quotesController));
router.post("/v1/quotes", quotesController.getQuotes.bind(quotesController));
router.get("/quote/:id",bypassValidation, quotesController.getQuoteById.bind(quotesController));
router.delete("/v1/quote/:id", quotesController.deleteQuote.bind(quotesController));
router.get("/v1/analysis", quotesController.getQuotesAnalysis.bind(quotesController));
router.get("/v1/analysis-graph", quotesController.getQuoteStatusGraphData.bind(quotesController));
router.put("/update-cust-quote-status-data", bypassValidation, quotesController.updateCustomerQuoteStatus.bind(quotesController));
router.get("/v1/quote-analysis",quotesController.getQuoteAnalysisQuoteId.bind(quotesController));
router.post("/v1/follow-up",quotesController.sendQuoteFollowUp.bind(quotesController));
router.post("/v1/close-quote-alert",quotesController.sendCloseAlert.bind(quotesController));
router.post("/v1/review-feedback",quotesController.sendReviewAndFeedback.bind(quotesController));
router.get("/v1/signed-url", quotesController.getSignedUrl.bind(quotesController));
router.post("/v1/get-unique_customers-quote-history", quotesController.getUniqueCustomersQuoteHistory.bind(quotesController));
router.post("/v1/get-kanban-quotes",quotesController.getKanbanQuotes.bind(quotesController));
router.post("/v1/move-kanban",quotesController.updateKanbanMovement.bind(quotesController));
router.get("/v1/get-sender-list",quotesController.quoteSenderNames.bind(quotesController));
router.post("/v1/update-install-status",quotesController.updateInstallStatus.bind(quotesController));
router.post("/v1/mark-stock-ordered", quotesController.markStockOrdered.bind(quotesController));
router.post("/v1/schedule-installation", quotesController.scheduleInstallation.bind(quotesController));
router.post("/v1/reschedule-installation", quotesController.rescheduleInstallation.bind(quotesController));
router.post("/v1/cancel-project", quotesController.cancelProject.bind(quotesController));
router.post("/v1/pipeline-counts", quotesController.getPipelineCounts.bind(quotesController));
router.post("/v1/close-job", quotesController.closeQuoteJob.bind(quotesController));
export default router;