/** Master Task / Follow-up / Escalation constants */

export enum TaskPriority {
	LOW = "LOW",
	NORMAL = "NORMAL",
	MEDIUM = "MEDIUM",
	HIGH = "HIGH",
	URGENT = "URGENT",
	CRITICAL = "CRITICAL",
}

export enum MasterTaskStatus {
	NEW = "NEW",
	ASSIGNED = "ASSIGNED",
	PENDING = "PENDING",
	IN_PROGRESS = "IN_PROGRESS",
	WAITING_CUSTOMER = "WAITING_CUSTOMER",
	WAITING_INSTALLER = "WAITING_INSTALLER",
	WAITING_SUPPLIER = "WAITING_SUPPLIER",
	WAITING_DNSP = "WAITING_DNSP",
	WAITING_FINANCE = "WAITING_FINANCE",
	WAITING_DOCUMENTS = "WAITING_DOCUMENTS",
	FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED",
	ON_HOLD = "ON_HOLD",
	COMPLETED = "COMPLETED",
	CANCELLED = "CANCELLED",
	/** Legacy — overdue is now a computed flag; keep for existing rows */
	OVERDUE = "OVERDUE",
	ESCALATED = "ESCALATED",
	/** Legacy */
	DONE = "DONE",
	PARTIALLY_DONE = "PARTIALLY_DONE",
}

export const TASK_OPEN_STATUSES = [
	MasterTaskStatus.NEW,
	MasterTaskStatus.ASSIGNED,
	MasterTaskStatus.PENDING,
	MasterTaskStatus.IN_PROGRESS,
	MasterTaskStatus.WAITING_CUSTOMER,
	MasterTaskStatus.WAITING_INSTALLER,
	MasterTaskStatus.WAITING_SUPPLIER,
	MasterTaskStatus.WAITING_DNSP,
	MasterTaskStatus.WAITING_FINANCE,
	MasterTaskStatus.WAITING_DOCUMENTS,
	MasterTaskStatus.FOLLOW_UP_REQUIRED,
	MasterTaskStatus.ON_HOLD,
	MasterTaskStatus.OVERDUE,
	MasterTaskStatus.ESCALATED,
	MasterTaskStatus.PARTIALLY_DONE,
];

export const TASK_DONE_STATUSES = [MasterTaskStatus.COMPLETED, MasterTaskStatus.DONE, MasterTaskStatus.CANCELLED];

export type TaskTypeDef = {
	code: string;
	label: string;
	category: string;
};

export const DEFAULT_TASK_TYPES: TaskTypeDef[] = [
	// Payments / Finance
	{ code: "PAYMENT", label: "Payment", category: "Finance" },
	{ code: "DEPOSIT", label: "Deposit", category: "Finance" },
	{ code: "DEPOSIT_PENDING", label: "Deposit Pending", category: "Finance" },
	{ code: "FINAL_PAYMENT", label: "Final Payment", category: "Finance" },
	{ code: "FINANCE", label: "Finance", category: "Finance" },
	{ code: "LOAN_APPLICATION", label: "Loan Application", category: "Finance" },
	{ code: "FINANCE_APPROVAL", label: "Finance Approval", category: "Finance" },
	{ code: "FINANCE_ISSUE", label: "Finance Issue", category: "Finance" },
	{ code: "FINANCE_APPLICATION", label: "Finance Application", category: "Finance" },
	{ code: "DOCUMENT_COLLECTION", label: "Document Collection", category: "Finance" },
	{ code: "FINANCE_FOLLOW_UP", label: "Finance Follow-up", category: "Finance" },
	{ code: "APPROVAL_FOLLOW_UP", label: "Approval Follow-up", category: "Finance" },
	{ code: "PAYMENT_FOLLOW_UP", label: "Payment Follow-up", category: "Finance" },
	{ code: "REFUND", label: "Refund", category: "Finance" },
	{ code: "INVOICE", label: "Invoice", category: "Finance" },
	{ code: "INVOICE_ISSUE", label: "Invoice Issue", category: "Finance" },
	{ code: "ACCOUNTS", label: "Accounts", category: "Finance" },
	// Customer
	{ code: "CUSTOMER_ISSUE", label: "Customer Issue", category: "Customer Support" },
	{ code: "CUSTOMER_COMPLAINT", label: "Customer Complaint", category: "Customer Support" },
	{ code: "CUSTOMER_FOLLOW_UP", label: "Customer Follow-Up", category: "Customer Support" },
	{ code: "CUSTOMER_CALLBACK", label: "Customer Call Back", category: "Customer Support" },
	{ code: "CUSTOMER_EMAIL", label: "Customer Email", category: "Customer Support" },
	{ code: "SMS_FOLLOW_UP", label: "SMS Follow-Up", category: "Customer Support" },
	{ code: "ISSUE_RESOLUTION", label: "Issue Resolution", category: "Customer Support" },
	{ code: "FEEDBACK", label: "Feedback", category: "Customer Support" },
	{ code: "CUSTOMER_SUPPORT", label: "Customer Support", category: "Customer Support" },
	{ code: "REVIEW_REQUEST", label: "Review Request", category: "Customer Support" },
	{ code: "REFERRAL", label: "Referral", category: "Customer Support" },
	{ code: "CANCELLATION", label: "Cancellation", category: "Customer Support" },
	{ code: "WARRANTY", label: "Warranty", category: "Customer Support" },
	// Sales / Quote
	{ code: "SALES", label: "Sales", category: "Sales" },
	{ code: "QUOTE", label: "Quote", category: "Sales" },
	{ code: "QUOTE_REVISION", label: "Quote Revision", category: "Sales" },
	{ code: "QUOTE_FOLLOW_UP", label: "Quote Follow-Up", category: "Sales" },
	{ code: "QUOTE_SIGNING", label: "Quote Signing", category: "Sales" },
	{ code: "LEAD_CALL", label: "Lead Call", category: "Sales" },
	{ code: "FOLLOW_UP", label: "Follow-up", category: "Sales" },
	{ code: "APPOINTMENT", label: "Appointment", category: "Sales" },
	{ code: "CLOSING", label: "Closing", category: "Sales" },
	{ code: "LEAD_VISIT", label: "Lead Visit", category: "Sales" },
	{ code: "LEAD_CONVERSION", label: "Lead Conversion", category: "Sales" },
	{ code: "LEAD_FOLLOW_UP", label: "Lead Follow-up", category: "Sales" },
	{ code: "MARKETING", label: "Marketing", category: "Sales" },
	// Installation / Operations
	{ code: "JOB_ASSIGNMENT", label: "Job Assignment", category: "Operations" },
	{ code: "INSTALLER_ASSIGNMENT", label: "Installer Assignment", category: "Operations" },
	{ code: "INSTALLER_ISSUE", label: "Installer Issue", category: "Operations" },
	{ code: "INSTALLATION_ISSUE", label: "Installation Issue", category: "Operations" },
	{ code: "INSTALLATION_FOLLOW_UP", label: "Installation Follow-Up", category: "Operations" },
	{ code: "INSTALLATION_BOOKING", label: "Installation Booking", category: "Operations" },
	{ code: "INSTALLATION_DATE_CONFIRMATION", label: "Installation Date Confirmation", category: "Operations" },
	{ code: "RESCHEDULE", label: "Reschedule", category: "Operations" },
	{ code: "JOB_REVIEW", label: "Job Review", category: "Operations" },
	{ code: "PRE_APPROVAL", label: "Pre-Approval", category: "Operations" },
	{ code: "GRID_CONNECTION", label: "Grid Connection", category: "Operations" },
	{ code: "GRID_ISSUE", label: "Grid Issue", category: "Operations" },
	{ code: "GRID_APPROVAL", label: "Grid Approval", category: "Operations" },
	{ code: "DNSP_ISSUE", label: "DNSP Issue", category: "Operations" },
	{ code: "SOLAR_APPROVAL", label: "Solar Approval", category: "Operations" },
	{ code: "BATTERY_APPROVAL", label: "Battery Approval", category: "Operations" },
	{ code: "INSTALLER_COORDINATION", label: "Installer Coordination", category: "Operations" },
	{ code: "INSTALLATION_SCHEDULING", label: "Installation Scheduling", category: "Operations" },
	{ code: "INSTALLATION_COMPLETION", label: "Installation Completion", category: "Operations" },
	{ code: "COMPLIANCE_DOCUMENTS", label: "Compliance Documents", category: "Operations" },
	{ code: "COMPLIANCE", label: "Compliance", category: "Operations" },
	{ code: "COMPLIANCE_ISSUE", label: "Compliance Issue", category: "Operations" },
	{ code: "SLA_DELAY_RESOLVE", label: "Resolve Delayed Job", category: "Operations" },
	{ code: "INSTALLATION_VISIT", label: "Installation Visit", category: "Operations" },
	{ code: "INSTALLATION_SERVICE", label: "Installation Service", category: "Operations" },
	{ code: "SITE_INSPECTION", label: "Site Inspection", category: "Operations" },
	{ code: "SITE_PHOTOS_REQUIRED", label: "Site Photos Required", category: "Operations" },
	{ code: "INSTALLER_PHOTOS_REQUIRED", label: "Installer Photos Required", category: "Operations" },
	{ code: "CUSTOMER_PHOTOS_REQUIRED", label: "Customer Photos Required", category: "Operations" },
	{ code: "CUSTOMER_DOCUMENTATION", label: "Customer Documentation", category: "Operations" },
	{ code: "MISSING_DOCUMENT", label: "Missing Document", category: "Operations" },
	// Technical
	{ code: "TECHNICAL_ISSUE", label: "Technical Issue", category: "Technical" },
	{ code: "PRODUCT_FAULT", label: "Product Fault", category: "Technical" },
	{ code: "METER", label: "Meter", category: "Technical" },
	{ code: "SMART_METER", label: "Smart Meter", category: "Technical" },
	{ code: "SWITCHBOARD", label: "Switchboard", category: "Technical" },
	{ code: "ELECTRICAL_ISSUE", label: "Electrical Issue", category: "Technical" },
	{ code: "BATTERY_ISSUE", label: "Battery Issue", category: "Technical" },
	{ code: "SOLAR_PANEL_ISSUE", label: "Solar Panel Issue", category: "Technical" },
	{ code: "INVERTER_ISSUE", label: "Inverter Issue", category: "Technical" },
	{ code: "BACKUP_ISSUE", label: "Backup Issue", category: "Technical" },
	// Stock / Delivery
	{ code: "STOCK", label: "Stock", category: "Stock" },
	{ code: "STOCK_ORDER", label: "Stock Order", category: "Stock" },
	{ code: "STOCK_ISSUE", label: "Stock Issue", category: "Stock" },
	{ code: "PRODUCT_AVAILABILITY", label: "Product Availability", category: "Stock" },
	{ code: "DELIVERY", label: "Delivery", category: "Stock" },
	{ code: "DELIVERY_ISSUE", label: "Delivery Issue", category: "Stock" },
	{ code: "DELIVERY_FOLLOW_UP", label: "Delivery Follow-Up", category: "Stock" },
	{ code: "SUPPLIER_ISSUE", label: "Supplier Issue", category: "Stock" },
	{ code: "WAREHOUSE", label: "Warehouse", category: "Stock" },
	// Rebate
	{ code: "REBATE", label: "Rebate", category: "Rebate" },
	{ code: "STC", label: "STC", category: "Rebate" },
	{ code: "BATTERY_REBATE", label: "Battery Rebate", category: "Rebate" },
	{ code: "SOLAR_VICTORIA", label: "Solar Victoria", category: "Rebate" },
	// HR / Internal
	{ code: "EMPLOYEE_TASK", label: "Employee Task", category: "HR" },
	{ code: "ATTENDANCE_ISSUE", label: "Attendance Issue", category: "HR" },
	{ code: "TRAINING", label: "Training", category: "HR" },
	{ code: "PERFORMANCE_REVIEW", label: "Performance Review", category: "HR" },
	{ code: "RECRUITMENT", label: "Recruitment", category: "HR" },
	{ code: "INTERVIEW", label: "Interview", category: "HR" },
	{ code: "ONBOARDING", label: "Onboarding", category: "HR" },
	{ code: "HR", label: "HR", category: "HR" },
	{ code: "MEETING", label: "Meeting", category: "General" },
	{ code: "INTERNAL_OPERATIONS", label: "Internal Operations", category: "General" },
	{ code: "INTERNAL_TASK", label: "Internal Task", category: "General" },
	{ code: "MANAGEMENT", label: "Management", category: "General" },
	{ code: "MANAGEMENT_TASK", label: "Management Task", category: "General" },
	{ code: "OTHER", label: "Other", category: "General" },
];

export const FOLLOW_UP_OUTCOMES = [
	"CUSTOMER_INTERESTED",
	"CALLBACK_REQUESTED",
	"QUOTE_SENT",
	"WAITING_FOR_CUSTOMER",
	"FINANCE_PENDING",
	"NOT_INTERESTED",
	"SOLD",
	"LOST",
	"RESCHEDULE",
] as const;

export const DEFAULT_ESCALATION_RULES = [
	{ task_type: "FOLLOW_UP", warning_hours: 2, escalate_l1_hours: 6, escalate_l2_hours: 24, escalate_l3_hours: 48 },
	{ task_type: "LEAD_FOLLOW_UP", warning_hours: 2, escalate_l1_hours: 6, escalate_l2_hours: 24, escalate_l3_hours: 48 },
	{ task_type: "QUOTE_FOLLOW_UP", warning_hours: 4, escalate_l1_hours: 12, escalate_l2_hours: 24, escalate_l3_hours: 48 },
	{ task_type: "FINANCE_APPLICATION", warning_hours: 24, escalate_l1_hours: 48, escalate_l2_hours: 72, escalate_l3_hours: 96 },
	{ task_type: "PRE_APPROVAL", warning_hours: 24, escalate_l1_hours: 48, escalate_l2_hours: 72, escalate_l3_hours: 96 },
	{ task_type: "GRID_CONNECTION", warning_hours: 48, escalate_l1_hours: 72, escalate_l2_hours: 96, escalate_l3_hours: 120 },
	{ task_type: "CUSTOMER_COMPLAINT", warning_hours: 4, escalate_l1_hours: 24, escalate_l2_hours: 48, escalate_l3_hours: 72 },
	{ task_type: "COMPLIANCE_DOCUMENTS", warning_hours: 12, escalate_l1_hours: 24, escalate_l2_hours: 48, escalate_l3_hours: 72 },
	{ task_type: "SLA_DELAY_RESOLVE", warning_hours: 6, escalate_l1_hours: 12, escalate_l2_hours: 24, escalate_l3_hours: 48 },
	{ task_type: "*", warning_hours: 24, escalate_l1_hours: 48, escalate_l2_hours: 72, escalate_l3_hours: 96 },
];

export const MASTER_TASK_MANAGER_ROLES = new Set([
	"SUPER_ADMIN",
	"ADMIN",
	"CEO",
	"MANAGER",
	"OPERATIONS_MANAGER",
	"ACCOUNTS_MANAGER",
	"HR_EXECUTIVE",
]);

export const MASTER_TASK_STATUS_LABELS: Record<string, string> = {
	NEW: "New",
	ASSIGNED: "Assigned",
	PENDING: "Pending",
	IN_PROGRESS: "In Progress",
	WAITING_CUSTOMER: "Waiting for Customer",
	WAITING_INSTALLER: "Waiting for Installer",
	WAITING_SUPPLIER: "Waiting for Supplier",
	WAITING_DNSP: "Waiting for Grid / DNSP",
	WAITING_FINANCE: "Waiting for Finance",
	WAITING_DOCUMENTS: "Waiting for Documents",
	FOLLOW_UP_REQUIRED: "Follow-Up Required",
	ON_HOLD: "On Hold",
	ESCALATED: "Escalated",
	COMPLETED: "Completed",
	CANCELLED: "Cancelled",
	OVERDUE: "Overdue",
	DONE: "Completed",
	PARTIALLY_DONE: "Partially Done",
};
