export enum TaskType {
  OTHER = "OTHER",
  LEAD_VISIT = "LEAD_VISIT",
  LEAD_CONVERSION = "LEAD_CONVERSION",
  SLA_DELAY_RESOLVE = "SLA_DELAY_RESOLVE",
}

export enum TaskStatus {
  PENDING = "PENDING",
  DONE = "DONE",
  PARTIALLY_DONE = "PARTIALLY_DONE"
}

export enum CustomerStatus {
  INTERESTED = "INTERESTED",
  NOT_INTERESTED = "NOT_INTERESTED"
}
