/** Default Som's Energy state companies — seeded when collection is empty. */
export const DEFAULT_CRM_COMPANY_UNITS = [
	{
		company_name: "Soms Energy Victoria Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "VIC",
		abn: "58 684 462 646",
		business_address: "Suite 535/1 Queens Road, Melbourne VIC 3004",
		postal_address: "Suite 535/1 Queens Road, Melbourne VIC 3004",
		email: "info@somsenergy.com.au",
		support_email: "info@somsenergy.com.au",
		sales_email: "sales@somsenergy.com.au",
		mobile: "+61480582628",
		phone: "+61480582628",
		website: "https://www.somsenergy.com.au",
		invoice_prefix: "INV-VIC",
		quote_prefix: "QT-VIC",
		job_prefix: "JOB-VIC",
		receipt_prefix: "RCP-VIC",
		proposal_prefix: "PROP-VIC",
		sort_order: 1,
		state_config: {
			solar_vic_enabled: true,
			stc_enabled: true,
			veec_enabled: true,
			battery_rebate_enabled: true,
		},
	},
	{
		company_name: "Soms Energy NSW Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "NSW",
		abn: "",
		business_address: "",
		email: "info@somsenergy.com.au",
		invoice_prefix: "INV-NSW",
		quote_prefix: "QT-NSW",
		sort_order: 2,
		state_config: { pdrs_enabled: true, stc_enabled: true, battery_rebate_enabled: true },
	},
	{
		company_name: "Soms Energy ACT Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "ACT",
		abn: "",
		invoice_prefix: "INV-ACT",
		quote_prefix: "QT-ACT",
		sort_order: 3,
		state_config: { sustainable_household_scheme_enabled: true, stc_enabled: true },
	},
	{
		company_name: "Soms Energy WA Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "WA",
		abn: "",
		invoice_prefix: "INV-WA",
		quote_prefix: "QT-WA",
		sort_order: 4,
		state_config: { wa_battery_scheme_enabled: true, stc_enabled: true },
	},
	{
		company_name: "Soms Energy QLD Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "QLD",
		abn: "",
		invoice_prefix: "INV-QLD",
		quote_prefix: "QT-QLD",
		sort_order: 5,
		state_config: { stc_enabled: true, battery_rebate_enabled: true },
	},
	{
		company_name: "Soms Energy SA Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "SA",
		abn: "",
		invoice_prefix: "INV-SA",
		quote_prefix: "QT-SA",
		sort_order: 6,
		state_config: { stc_enabled: true },
	},
	{
		company_name: "Soms Energy TAS Pty Ltd",
		trading_name: "Soms Energy",
		state_code: "TAS",
		abn: "",
		invoice_prefix: "INV-TAS",
		quote_prefix: "QT-TAS",
		sort_order: 7,
		state_config: { stc_enabled: true },
	},
] as const;
