import mongoose, { Schema } from "mongoose";
import { applyBasePlugins, collectionOptions } from "@db/plugins";

const AssessmentSchema = new Schema(
  {
    id: { type: Number, unique: true, index: true },
    customer_id: { type: Number, required: true },
    sender_id: { type: Number, required: true },
    services: { type: Schema.Types.Mixed, required: true },
    fullName: { type: String },
    mobile: { type: String },
    email: { type: String },
    address: { type: String },
    postcode: { type: String },
    propertyType: { type: String },
    ownership: { type: String },
    installTimeframe: { type: String },
    customDate: { type: Date },
    siteAccess: { type: String },
    parking: { type: String },
    pets: { type: String },
    supplyType: { type: String },
    switchboardLocation: { type: String },
    customSwitchboardLocation: { type: String },
    meterType: { type: String },
    customMeterType: { type: String },
    existingSolar: { type: String },
    existingSolarDetails: { type: String },
    solarSystemSize: { type: Number },
    quarterlyBill: { type: String },
    customBillAmount: { type: Number },
    monitoring: { type: String },
    roofType: { type: String },
    storeys: { type: String },
    roofCondition: { type: String },
    shading: { type: String },
    batteryLocation: { type: String },
    customBatteryLocation: { type: String },
    batteryDistance: { type: Number },
    airconType: { type: String },
    indoorUnits: { type: Number },
    rooms: { type: String },
    customRooms: { type: String },
    existingAircon: { type: String },
    existingAirconDetails: { type: String },
    hotWaterType: { type: String },
    heatPumpLocation: { type: String },
    customHeatPumpLocation: { type: String },
    tankSize: { type: String },
    customTankSize: { type: Number },
    switchboardIssues: { type: String },
    asbestosRisk: { type: String },
    accessConstraints: { type: String },
    signaturePhoto: { type: String },
    billPhoto: { type: String },
    meterPhoto: { type: String },
    switchboardOpenPhoto: { type: String },
    switchboardClosedPhoto: { type: String },
    roofFrontPhoto: { type: String },
    roofWidePhoto: { type: String },
    shadingObjectsPhoto: { type: String },
    batteryWallPhoto: { type: String },
    batteryClearancePhoto: { type: String },
    batteryPathPhoto: { type: String },
    airconIndoorPhoto: { type: String },
    airconOutdoorPhoto: { type: String },
    airconRoutePhoto: { type: String },
    hotWaterSystemPhoto: { type: String },
    heatPumpLocationPhoto: { type: String },
    heatPumpDrainPhoto: { type: String },
    confirmAccuracy: { type: Boolean },
    confirmPermission: { type: Boolean },
    token: { type: String },
    status: { type: String, required: true, default: "PENDING" },
    existingPanels: { type: String },
    panelPlan: { type: String },
    panelCount: { type: Number },
    panelInstallYear: { type: String },
    propertyAge: { type: String },
    existingHeatingSystem: { type: String },
    airconPreference: { type: String },
    multiHeadWallScope: { type: String },
    condensatePumpNeeded: { type: String },
    floorPlanPhoto: { type: String },
    reviewedBy: { type: Number },
    reviewedAt: { type: Date },
    notes: { type: String },
  },
  collectionOptions("assessments"),
);

AssessmentSchema.virtual("customer", { ref: "User", localField: "customer_id", foreignField: "id", justOne: true });
AssessmentSchema.virtual("sender", { ref: "User", localField: "sender_id", foreignField: "id", justOne: true });

applyBasePlugins(AssessmentSchema, { collection: "assessments", paranoid: true });

const Assessment = mongoose.models.Assessment ?? mongoose.model("Assessment", AssessmentSchema);
export default Assessment;
